package javaapplication1;

import java.util.ArrayList;

public class OyunArayuz extends javax.swing.JFrame {

    // Oyuncu ve Bilgisayar Nesneleri
    Oyuncu oyuncu = new Oyuncu(1, "Kullanici", 0);
    Oyuncu bilgisayar = new Oyuncu(2, "Bilgisayar", 0);
    Oyun oyun;
    int hamleSayisi;
    int kazanan = 0;

    public OyunArayuz() {
        initComponents();
    }

    public void OyuncuListeGuncelle() {
        // Ekran Guncelle
        ArrayList<SavasAraclari> oyuncuKartListesi = oyuncu.getKartListesi();

        ArrayList<String> oyuncuKartListesiString = new ArrayList<>();
        String kartBilgileri;
        for (SavasAraclari kart : oyuncuKartListesi) {
            kartBilgileri = kart.KartPuaniGoster();
            oyuncuKartListesiString.add(kartBilgileri);
        }

        oyuncuKartlarList.setListData(oyuncuKartListesiString.toArray(String[]::new));
    }

    public void OyunBitti(int kazanan) {
        String oyunBittiDurum = oyun.OyunuSonlandir(kazanan);

        int response = javax.swing.JOptionPane.showConfirmDialog(null, oyunBittiDurum + "\nSkorlar:\nOyuncu: " + oyuncu.getSkor() + "\nBilgisayar: " + bilgisayar.getSkor() + "\nOyundan Cik?", "Oyun Bitti!", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);

        // Uyarı penceresinde "Evet" seçildiğinde uygulamayı kapat
        if (response == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);  // Uygulama sonlanır
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        baslangicSeviyeTextField = new javax.swing.JTextField();
        maksimumHamleTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        baslaButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        hamleYapButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bilgisayarKartlarTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        oyuncuKartlarTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        karsilasmaTextArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        bilgisayarHamleTextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        oyuncuHamleTextArea = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        oyuncuKartlarList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hamleBitirButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        bilgisayarSkorLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        oyuncuSkorLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        hamleSayisiLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1650, 700));
        setMinimumSize(new java.awt.Dimension(1650, 700));
        setPreferredSize(new java.awt.Dimension(1650, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1650, 700));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Savas Araclari Oyunu");

        baslangicSeviyeTextField.setText("0");
        baslangicSeviyeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baslangicSeviyeTextFieldActionPerformed(evt);
            }
        });

        maksimumHamleTextField.setText("5");

        jLabel1.setText("Baslangic Seviye Puani:");

        jLabel3.setText("Maksimum Hamle Sayisi:");

        baslaButton.setText("Oyuna Basla");
        baslaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baslaButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Oyuncu Kartlari:");

        hamleYapButton.setText("Hamle Yap!");
        hamleYapButton.setEnabled(false);
        hamleYapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamleYapButtonActionPerformed(evt);
            }
        });

        bilgisayarKartlarTextArea.setEditable(false);
        bilgisayarKartlarTextArea.setColumns(20);
        bilgisayarKartlarTextArea.setRows(5);
        jScrollPane2.setViewportView(bilgisayarKartlarTextArea);

        oyuncuKartlarTextArea.setEditable(false);
        oyuncuKartlarTextArea.setColumns(20);
        oyuncuKartlarTextArea.setRows(5);
        jScrollPane3.setViewportView(oyuncuKartlarTextArea);

        karsilasmaTextArea.setEditable(false);
        karsilasmaTextArea.setColumns(20);
        karsilasmaTextArea.setRows(5);
        jScrollPane4.setViewportView(karsilasmaTextArea);

        bilgisayarHamleTextArea.setEditable(false);
        bilgisayarHamleTextArea.setColumns(20);
        bilgisayarHamleTextArea.setRows(5);
        jScrollPane5.setViewportView(bilgisayarHamleTextArea);

        oyuncuHamleTextArea.setEditable(false);
        oyuncuHamleTextArea.setColumns(20);
        oyuncuHamleTextArea.setRows(5);
        jScrollPane6.setViewportView(oyuncuHamleTextArea);

        oyuncuKartlarList.setToolTipText("");
        jScrollPane7.setViewportView(oyuncuKartlarList);

        jLabel5.setText("Bilgisayarin Sectigi Kartlar:");

        jLabel6.setText("Oyuncunun Sectigi Kartlar:");

        jLabel7.setText("Karsılasma:");

        jLabel8.setText("Hamle Sonrasi Bilgisayarin Sectigi Kartlar:");

        jLabel9.setText("Hamle Sonrasi Oyuncunun Sectigi Kartlar");

        hamleBitirButton.setText("Hamle Bitir!");
        hamleBitirButton.setEnabled(false);
        hamleBitirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamleBitirButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Bilgisayar Skoru:");

        bilgisayarSkorLabel.setText("0");

        jLabel11.setText("Oyuncu Skoru:");

        oyuncuSkorLabel.setText("0");

        jLabel12.setText("Hamle Sayısı:");

        hamleSayisiLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jScrollPane6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(298, 298, 298)
                                .addComponent(hamleBitirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(351, 351, 351)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bilgisayarSkorLabel)
                                        .addGap(116, 116, 116)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(oyuncuSkorLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hamleSayisiLabel)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(134, 134, 134)
                                        .addComponent(jLabel2)
                                        .addGap(295, 295, 295)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(baslangicSeviyeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(maksimumHamleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(15, 24, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hamleYapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addComponent(baslaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(baslangicSeviyeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(maksimumHamleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(baslaButton))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hamleYapButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hamleBitirButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(hamleSayisiLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(bilgisayarSkorLabel)
                            .addComponent(jLabel11)
                            .addComponent(oyuncuSkorLabel))))
                .addContainerGap())
        );

        baslangicSeviyeTextField.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baslangicSeviyeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baslangicSeviyeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baslangicSeviyeTextFieldActionPerformed

    private void baslaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baslaButtonActionPerformed
        int baslangicSeviyePuani = Integer.parseInt(baslangicSeviyeTextField.getText());
        int maksimumHamleSayisi = Integer.parseInt(maksimumHamleTextField.getText());

        // Oyun Nesnesi
        oyun = new Oyun(oyuncu, bilgisayar, maksimumHamleSayisi);
        oyun.Baslat(baslangicSeviyePuani);

        OyuncuListeGuncelle();

        // Secim Bekle - Secim Tusu Aktiflestir ve Deaktifleştir
        hamleYapButton.setEnabled(true);
        baslaButton.setEnabled(false);
        baslangicSeviyeTextField.setEnabled(false);
        maksimumHamleTextField.setEnabled(false);
    }//GEN-LAST:event_baslaButtonActionPerformed

    private void hamleYapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamleYapButtonActionPerformed
        // Hamle Sayisi
        hamleSayisi = Integer.parseInt(hamleSayisiLabel.getText());

        // Oyuncu Seçim Yapıyor - Secilen Kart Sayısını Kontrol Et
        int[] secimler = oyuncuKartlarList.getSelectedIndices();
        if (secimler.length == 3) {
            ArrayList<SavasAraclari> oyuncuSecilenKartlar = oyun.KartSecimi(oyuncu, secimler);

            // Kart Secimi Kontrolü
            if (!oyuncuSecilenKartlar.isEmpty()) {
                // Bilgisayar Kart Seciyor
                System.out.println("Bilgisayar Kartlarini Seciyor...");
                bilgisayar.KartlariGoster();
                System.out.println("---");
                ArrayList<SavasAraclari> bilgisayarSecilenKartlar = bilgisayar.KartSecRandom();
                System.out.println("Bilgisayar Kartlarini Secti!");

                String[][] karsilasanKartlar = oyun.HamleYap(hamleSayisi, oyuncuSecilenKartlar, bilgisayarSecilenKartlar);
                hamleSayisi++;

                // Karsilasan Kartlari Ekranda Goster
                oyuncuKartlarTextArea.setText(karsilasanKartlar[0][0] + "\n" + karsilasanKartlar[0][1] + "\n" + karsilasanKartlar[0][2]);
                bilgisayarKartlarTextArea.setText(karsilasanKartlar[1][0] + "\n" + karsilasanKartlar[1][1] + "\n" + karsilasanKartlar[1][2]);

                // Hasarları Goster
                karsilasmaTextArea.setText("1. Karsilasma: \nOzel Hasar Durumu:\nOyuncudan Bilgisayar Kartina: " + karsilasanKartlar[8][0] + "\nBilgisayardan Oyuncu Kartina: " + karsilasanKartlar[8][1] + "\nOyuncudan Bilgisayar Kartina Hasar: " + karsilasanKartlar[7][0] + "\n" + "Bilgisayardan Oyuncu Kartina Hasar: " + karsilasanKartlar[7][1] + "\n\n2. Karsilasma: \nOzel Hasar Durumu:\nOyuncudan Bilgisayar Kartina: " + karsilasanKartlar[8][2] + "\nBilgisayardan Oyuncu Kartina: " + karsilasanKartlar[8][3] + "\nOyuncudan Bilgisayar Kartina Hasar: " + karsilasanKartlar[7][2] + "\n" + "Bilgisayardan Oyuncu Kartina Hasar: " + karsilasanKartlar[7][3] + "\n\n3. Karsilasma: \nOzel Hasar Durumu:\nOyuncudan Bilgisayar Kartina: " + karsilasanKartlar[8][4] + "\nBilgisayardan Oyuncu Kartina: " + karsilasanKartlar[8][5] + "\nOyuncudan Bilgisayar Kartina Hasar: " + karsilasanKartlar[7][4] + "\n" + "Bilgisayardan Oyuncu Kartina Hasar: " + karsilasanKartlar[7][5]);

                // Karşılaşma Sonrası Kartları Ekranda Göster
                oyuncuHamleTextArea.setText(karsilasanKartlar[2][0] + karsilasanKartlar[5][0] + "\n" + karsilasanKartlar[2][1] + karsilasanKartlar[5][1] + "\n" + karsilasanKartlar[2][2] + karsilasanKartlar[5][2]);
                bilgisayarHamleTextArea.setText(karsilasanKartlar[3][0] + karsilasanKartlar[6][0] + "\n" + karsilasanKartlar[3][1] + karsilasanKartlar[6][1] + "\n" + karsilasanKartlar[3][2] + karsilasanKartlar[6][2]);

                // Skorları Goster
                oyuncuSkorLabel.setText(karsilasanKartlar[4][0]);
                bilgisayarSkorLabel.setText(karsilasanKartlar[4][1]);

                // Hamle Sayısını Ekranda Guncelle
                hamleSayisiLabel.setText(String.valueOf(hamleSayisi));

                // Hamle Bitir Buttonu Aktif Et ve Hamle Yap Button Deaktif Et
                hamleBitirButton.setEnabled(true);
                hamleYapButton.setEnabled(false);
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Tum Kartlari Birer Kez Secmeden Ayni Karti Tekrar Kullanamazsiniz!", "Uyarı", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "3 Kart Secmelisiniz!", "Uyarı", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_hamleYapButtonActionPerformed

    private void hamleBitirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamleBitirButtonActionPerformed
        // Ekranı Temizle, Kart Dağıt ve Oyuncu Kart Ekranını Güncelle
        oyuncuKartlarTextArea.setText("");
        bilgisayarKartlarTextArea.setText("");
        karsilasmaTextArea.setText("");
        oyuncuHamleTextArea.setText("");
        bilgisayarHamleTextArea.setText("");

        System.out.println("----Kalan Kartlar----");
        System.out.println("Oyuncu: " + oyuncu.getKartListesi().size() + " - Bilgisayar: " + bilgisayar.getKartListesi().size());

        // Oyun Bitti mi?
        // Karti biten var mi?
        if (oyuncu.getKartListesi().isEmpty()) {
            kazanan = 2;
            OyuncuListeGuncelle();
            OyunBitti(kazanan);
        } else if (bilgisayar.getKartListesi().isEmpty()) {
            kazanan = 1;
            OyuncuListeGuncelle();
            OyunBitti(kazanan);
        } else if (Integer.parseInt(hamleSayisiLabel.getText()) == Integer.parseInt(maksimumHamleTextField.getText())) { // Maksimum Hamle Bitti mi?
            OyuncuListeGuncelle();
            OyunBitti(kazanan);
        } else {
            // Yeni Kartlari Ver
            oyun.YeniKartVer(Integer.parseInt(baslangicSeviyeTextField.getText()));
            System.out.println("Birer Kart Verildi: " + oyuncu.getKartListesi().size() + " - " + bilgisayar.getKartListesi().size());

            // Kart Secilme Durumu Guncelle
            oyuncu.KartKontrolGuncelle();

            OyuncuListeGuncelle();

            // Secim Bekle - Secim Tusu Aktiflestir ve Deaktiflestir
            hamleYapButton.setEnabled(true);
            hamleBitirButton.setEnabled(false);
        }

    }//GEN-LAST:event_hamleBitirButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OyunArayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OyunArayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OyunArayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OyunArayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OyunArayuz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baslaButton;
    private javax.swing.JTextField baslangicSeviyeTextField;
    private javax.swing.JTextArea bilgisayarHamleTextArea;
    private javax.swing.JTextArea bilgisayarKartlarTextArea;
    private javax.swing.JLabel bilgisayarSkorLabel;
    private javax.swing.JButton hamleBitirButton;
    private javax.swing.JLabel hamleSayisiLabel;
    private javax.swing.JButton hamleYapButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea karsilasmaTextArea;
    private javax.swing.JTextField maksimumHamleTextField;
    private javax.swing.JTextArea oyuncuHamleTextArea;
    private javax.swing.JList<String> oyuncuKartlarList;
    private javax.swing.JTextArea oyuncuKartlarTextArea;
    private javax.swing.JLabel oyuncuSkorLabel;
    // End of variables declaration//GEN-END:variables
}
